name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'  # 每天同步一次
  workflow_dispatch:  # 也可以手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add upstream remote
        run: git remote add upstream https://github.com/lod61/edgetunnel.git

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Merge changes
        run: |
          git checkout main
          git merge upstream/main --allow-unrelated-histories -m "Syncing with upstream"

      - name: Push changes
        run: git push origin main
